id: PF4238277
initial_creation_type: input
source_metadata:
  title: Katok Rigdzin Tsewang Norbu
  language: bo
  description: 'Texts by Katok Rigdzin Tsewang Norbu (kaḥ thog rig ''dzin tshe dbang
    nor bu, 1698–1755):'
  volume:
    6e894e7e3fc6414e8f66842ba83f51e0:
      title: Advice for a King
      parent: Advice
created_at: '2022-03-01T00:15:32.942332'
last_modified_at: '2022-03-01T00:15:32.942335'
statistics:
  total_words: 259
  total_non_words: 21
quality:
  non_words_ratio: 0.08
